#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# Event nethserver-calibre-update 
#--------------------------------------------------

$event = 'nethserver-calibre-update';

event_actions($event, qw(
  initialize-default-databases 00
  nethserver-calibre-conf 20
));

event_templates($event, qw(
  /etc/httpd/conf.d/zz_calibre.conf
  /usr/lib/systemd/system/calibre.service
));

event_services($event, qw(
  httpd reload
  calibre restart
));

#--------------------------------------------------
# Event nethserver-calibre-save
#--------------------------------------------------

$event = 'nethserver-calibre-save';

event_actions($event, qw(
  nethserver-calibre-conf 20
));

event_templates($event, qw(
  /etc/httpd/conf.d/zz_calibre.conf
  /usr/lib/systemd/system/calibre.service
));

event_services($event, qw(
  httpd reload
  calibre restart
));

#--------------------------------------------------
# actions for tls-policy-save event
#--------------------------------------------------
#
# $event = 'tls-policy-save';
#
# event_templates($event, qw(
#   /etc/httpd/conf.d/zz_calibre.conf
# ));