#!/usr/bin/perl -w

use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# Event nethserver-calibre-update 
#--------------------------------------------------

$event = 'nethserver-calibre-update';

event_actions($event, qw(
  initialize-default-databases 00
  nethserver-calibre-conf 04
  nethserver-calibre-smb-conf 04
));

event_templates($event, qw(
  /etc/httpd/conf.d/default-virtualhost.inc
  /etc/httpd/conf.d/zz_calibre.conf
  /usr/lib/systemd/system/calibre.service
  /etc/samba/smb.conf
  /etc/cron.d/calibre
));

event_services($event, qw(
  httpd reload
  calibre restart
  smb reload
));

#--------------------------------------------------
# Event nethserver-calibre-save
#--------------------------------------------------

$event = 'nethserver-calibre-save';

event_actions($event, qw(
  nethserver-calibre-conf 04
  nethserver-calibre-smb-conf 04
));

event_templates($event, qw(
  /etc/httpd/conf.d/default-virtualhost.inc
  /etc/httpd/conf.d/zz_calibre.conf
  /usr/lib/systemd/system/calibre.service
  /etc/samba/smb.conf
  /etc/cron.d/calibre
));

event_services($event, qw(
  httpd reload
  calibre restart
  smb reload
));

#--------------------------------------------------
# Event nethserver-sssd-save
#--------------------------------------------------

$event = 'nethserver-sssd-save';

event_actions($event, qw(
  nethserver-calibre-smb-conf 04
));

event_templates($event, qw(
  /etc/samba/smb.conf
));

event_services($event, qw(
  smb reload
));

#--------------------------------------------------
# actions for tls-policy-save event
#--------------------------------------------------
#
# $event = 'tls-policy-save';
#
# event_templates($event, qw(
#   /etc/httpd/conf.d/zz_calibre.conf
# ));